name: ng_fontawesome
version: 5.7.2+2
description: >
  Contains directives for using glyphs from the popular Font Awesome library.
authors:
  - Mark E. Haase <mehaase@gmail.com>
homepage: https://github.com/hyperiongray/ng_fontawesome
environment:
  sdk: '>=2.2.0 <3.0.0'
dependencies:
  angular: '^5.2.0'
